from pydantic import BaseModel, Field


class SetPerformanceAndRiskTargetsOutput(BaseModel):
    """Pydantic model for set_performance_and_risk_targets node outputs."""
    annual_gross_return_target: float = (
        Field(..., description="Target annual gross return expressed as a decimal (e.g., 0.12 for 12%)")
    )
    volatility_limit_pct: float = (
        Field(..., description="Maximum acceptable annual volatility expressed as a percentage (e.g., 15 for 15%)")
    )
    sharpe_ratio_goal: float = (
        Field(..., description="Desired Sharpe ratio target for the fund")
    )
    max_drawdown_pct: float = (
        Field(..., description="Maximum acceptable peak\u2011to\u2011trough drawdown expressed as a percentage (e.g., 20 for 20%)")
    )


class EstimateSetupAndOperatingCostsOutput(BaseModel):
    """Pydantic model for estimate_setup_and_operating_costs node outputs."""
    service_provider_cost_usd: float = (
        Field(..., description="Estimated total annual cost in USD for all service providers listed")
    )
    technology_systems_cost_usd: float = (
        Field(..., description="Estimated total annual cost in USD for all required technology systems")
    )
    office_human_infrastructure_cost_usd: float = (
        Field(..., description="Estimated total annual cost in USD for office space, hardware, and human infrastructure")
    )


class DraftFeeStructureOutput(BaseModel):
    """Pydantic model for draft_fee_structure node outputs."""
    management_fee_percent: float = (
        Field(..., description="Management fee as a percentage of assets under management (AUM).")
    )
    performance_fee_percent: float = (
        Field(..., description="Performance fee as a percentage of returns generated by the fund.")
    )
    hurdle_rate_percent: float = (
        Field(..., description="Hurdle rate as a percentage of returns that must be achieved before performance fee is applied. Use 0 if not applicable.")
    )
    fee_commentary: str = (
        Field(..., description="Short explanatory sentence summarizing the fee structure and its alignment with fund objectives.")
    )


def draft_fee_structure(set_performance_and_risk_targets_input: SetPerformanceAndRiskTargetsOutput, estimate_setup_and_operating_costs_input: EstimateSetupAndOperatingCostsOutput, **kwargs) -> DraftFeeStructureOutput:
    """
    Generate a fee model based on target returns, risk limits, and operating
    cost estimates.

    Parameters
    ----------
    annual_gross_return_target : float
        Target annual gross return expressed as a decimal (e.g., 0.12 for
        12%).
    volatility_limit_pct : float
        Maximum acceptable annual volatility in percent.
    sharpe_ratio_goal : float
        Desired Sharpe ratio target for the fund.
    max_drawdown_pct : float
        Maximum acceptable peak‑to‑trough drawdown in percent.
    service_provider_cost_usd : float
        Estimated annual cost for all service providers.
    technology_systems_cost_usd : float
        Estimated annual cost for all required technology systems.
    office_human_infrastructure_cost_usd : float
        Estimated annual cost for office space, hardware, and human
        infrastructure.

    Returns
    -------
    dict
        A dictionary containing fee percentages and a brief commentary.

    Raises
    ------
    ValueError
        If any numeric input is negative or missing.
    TypeError
        If inputs are not of expected numeric types.

    Examples
    --------
    >>> draft_fee_structure(
    ...     annual_gross_return_target=0.15,
    ...     volatility_limit_pct=10,
    ...     sharpe_ratio_goal=1.5,
    ...     max_drawdown_pct=15,
    ...     service_provider_cost_usd=400000,
    ...     technology_systems_cost_usd=200000,
    ...     office_human_infrastructure_cost_usd=300000)
    >>> )
    {
      "management_fee_percent": 1.5,
      "performance_fee_percent": 20.0,
      "hurdle_rate_percent": 5.0,
      "fee_commentary": "A 1.5% AUM management fee and 20% performance fee above
    a 5% hurdle aligns with the 15% return target and cost structure."
    }

    >>> draft_fee_structure(
    ...     annual_gross_return_target=0.10,
    ...     volatility_limit_pct=12,
    ...     sharpe_ratio_goal=1.0,
    ...     max_drawdown_pct=20,
    ...     service_provider_cost_usd=250000,
    ...     technology_systems_cost_usd=150000,
    ...     office_human_infrastructure_cost_usd=200000)
    >>> )
    {
      "management_fee_percent": 1.25,
      "performance_fee_percent": 15.0,
      "hurdle_rate_percent": 0.0,
      "fee_commentary": "A 1.25% AUM fee and 15% performance fee with no hurdle
    accommodate the 10% return target and operating costs."
    }

    """
    return DraftFeeStructureOutput(
        management_fee_percent=0.0,
        performance_fee_percent=0.0,
        hurdle_rate_percent=0.0,
        fee_commentary="",
    )