from pydantic import BaseModel, Field
from typing import List


class ClarifyFundObjectivesOutput(BaseModel):
    """Pydantic model for clarify_fund_objectives node outputs."""
    investment_objectives: List[str] = (
        Field(..., description="A list of up to eight bullet points outlining the hedge fund's primary business objectives, covering investment purpose, risk/reward expectations, and target market differentiation.")
    )


class DefineInvestorProfileOutput(BaseModel):
    """Pydantic model for define_investor_profile node outputs."""
    investor_profile_characteristics: List[str] = (
        Field(..., description="List of 4 key characteristics of the target investor profile")
    )


class ChooseInvestmentStrategyOutput(BaseModel):
    """Pydantic model for choose_investment_strategy node outputs."""
    chosen_strategy: str = (
        Field(..., description="The specific hedge fund strategy selected from the predefined categories")
    )
    alignment_explanation: str = (
        Field(..., description="A one-sentence explanation of how the chosen strategy supports the fund's objectives")
    )


class SetPerformanceAndRiskTargetsOutput(BaseModel):
    """Pydantic model for set_performance_and_risk_targets node outputs."""
    annual_gross_return_target: float = (
        Field(..., description="Target annual gross return expressed as a decimal (e.g., 0.12 for 12%)")
    )
    volatility_limit_pct: float = (
        Field(..., description="Maximum acceptable annual volatility expressed as a percentage (e.g., 15 for 15%)")
    )
    sharpe_ratio_goal: float = (
        Field(..., description="Desired Sharpe ratio target for the fund")
    )
    max_drawdown_pct: float = (
        Field(..., description="Maximum acceptable peak\u2011to\u2011trough drawdown expressed as a percentage (e.g., 20 for 20%)")
    )


class DraftFeeStructureOutput(BaseModel):
    """Pydantic model for draft_fee_structure node outputs."""
    management_fee_percent: float = (
        Field(..., description="Management fee as a percentage of assets under management (AUM).")
    )
    performance_fee_percent: float = (
        Field(..., description="Performance fee as a percentage of returns generated by the fund.")
    )
    hurdle_rate_percent: float = (
        Field(..., description="Hurdle rate as a percentage of returns that must be achieved before performance fee is applied. Use 0 if not applicable.")
    )
    fee_commentary: str = (
        Field(..., description="Short explanatory sentence summarizing the fee structure and its alignment with fund objectives.")
    )


class DesignRiskManagementFrameworkOutput(BaseModel):
    """Pydantic model for design_risk_management_framework node outputs."""
    control_name: List[str] = (
        Field(..., description="Names of the quantitative risk controls implemented")
    )
    control_limit: List[float] = (
        Field(..., description="Numerical limit or threshold associated with each control (e.g., VaR in % of AUM, position size cap in % of portfolio)")
    )


class OutlineGovernanceStructureOutput(BaseModel):
    """Pydantic model for outline_governance_structure node outputs."""
    roles: List[str] = (
        Field(..., description="List of the five leadership roles defined for the fund")
    )
    duties: List[str] = (
        Field(..., description="One-sentence duty description corresponding to each role in the same order as the roles list")
    )


class CompilePitchDeckOutlineOutput(BaseModel):
    """Pydantic model for compile_pitch_deck_outline node outputs."""
    slide_titles: List[str] = (
        Field(..., description="An ordered list of the 10 slide titles for the investor pitch deck.")
    )


def compile_pitch_deck_outline(clarify_fund_objectives_input: ClarifyFundObjectivesOutput, define_investor_profile_input: DefineInvestorProfileOutput, choose_investment_strategy_input: ChooseInvestmentStrategyOutput, set_performance_and_risk_targets_input: SetPerformanceAndRiskTargetsOutput, draft_fee_structure_input: DraftFeeStructureOutput, design_risk_management_framework_input: DesignRiskManagementFrameworkOutput, outline_governance_structure_input: OutlineGovernanceStructureOutput, **kwargs) -> CompilePitchDeckOutlineOutput:
    """
    Generate a 10‑slide title list for an investor pitch deck.

    Parameters
    ----------
    investment_objectives : List[str]
        Bullet points from clarify_fund_objectives outlining the fund’s
        purpose, risk/reward, and market differentiation.
    investor_profile_characteristics : List[str]
        Four key traits defining the target investor demographic, sourced
        from define_investor_profile.
    chosen_strategy : str
        Primary hedge‑fund strategy selected in choose_investment_strategy.
    alignment_explanation : str
        One‑sentence rationale linking the chosen strategy to the fund’s
        objectives.
    annual_gross_return_target : float
        Target gross return (decimal) from set_performance_and_risk_targets.
    volatility_limit_pct : float
        Maximum acceptable volatility (percentage) from
        set_performance_and_risk_targets.
    sharpe_ratio_goal : float
        Desired Sharpe ratio from set_performance_and_risk_targets.
    max_drawdown_pct : float
        Maximum acceptable drawdown (percentage) from
        set_performance_and_risk_targets.
    management_fee_percent : float
        Management fee percentage (AUM) from draft_fee_structure.
    performance_fee_percent : float
        Performance fee percentage (returns) from draft_fee_structure.
    hurdle_rate_percent : float
        Hurdle rate percentage from draft_fee_structure.
    control_name : List[str]
        Names of quantitative risk controls from
        design_risk_management_framework.
    control_limit : List[float]
        Numerical limits for each risk control.
    roles : List[str]
        Five leadership roles from outline_governance_structure.
    duties : List[str]
        One‑sentence duty for each leadership role.

    Returns
    -------
    List[str]
        An ordered list of 10 slide titles.

    Raises
    ------
    ValueError
        If any required input list is empty or contains fewer items than
        expected.

    Examples
    --------
    >>> slide_titles = compile_pitch_deck_outline(
    ...     investment_objectives=['Generate alpha through market‑neutral
    strategies', 'Cap volatility at 12%'],
    ...     investor_profile_characteristics=['Institutional', 'North America',
    'Minimum $10M', 'Medium liquidity'],
    ...     chosen_strategy='market neutral',
    ...     alignment_explanation='Aligns with low volatility goal',
    ...     annual_gross_return_target=0.15,
    ...     volatility_limit_pct=12.0,
    ...     sharpe_ratio_goal=1.5,
    ...     max_drawdown_pct=18.0,
    ...     management_fee_percent=1.5,
    ...     performance_fee_percent=20.0,
    ...     hurdle_rate_percent=5.0,
    ...     control_name=['VaR limit', 'Position size cap'],
    ...     control_limit=[1.5, 5.0],
    ...     roles=['GP', 'CIO', 'CFO', 'Head of Ops', 'Chief Compliance'],
    ...     duties=['Oversight', 'Strategy', 'Finance', 'Operations',
    'Compliance']"                 ")
    ["1. Fund Objectives & Investment Thesis", "2. Target Investor Profile", "3.
    Core Investment Strategy", "4. Performance & Risk Targets", "5. Fee &
    Incentive Structure", "6. Quantitative Risk Controls", "7. Governance &
    Leadership", "8. Operations & Execution Model", "9. Timeline & Milestones",
    "10. Closing & Q&A"]

    >>> slide_titles = compile_pitch_deck_outline(
    ...     investment_objectives=['Alpha generation', 'Risk‑adjusted returns'],
    ...     investor_profile_characteristics=['Institutional', 'Europe',
    'Minimum $5M', 'High liquidity'],
    ...     chosen_strategy='global macro',
    ...     alignment_explanation='Supports alpha generation via macro
    exposure',
    ...     annual_gross_return_target=0.18,
    ...     volatility_limit_pct=15.0,
    ...     sharpe_ratio_goal=1.8,
    ...     max_drawdown_pct=20.0,
    ...     management_fee_percent=2.0,
    ...     performance_fee_percent=25.0,
    ...     hurdle_rate_percent=7.0,
    ...     control_name=['Liquidity threshold'],
    ...     control_limit=[10.0],
    ...     roles=['GP', 'CIO', 'CFO', 'Head of Ops', 'Compliance Officer'],
    ...     duties=['Oversight', 'Strategy', 'Finance', 'Operations',
    'Compliance']
    >>> )
    ["1. Fund Objectives & Investment Thesis", "2. Target Investor Profile", "3.
    Core Investment Strategy", "4. Performance & Risk Targets", "5. Fee &
    Incentive Structure", "6. Quantitative Risk Controls", "7. Governance &
    Leadership", "8. Operations & Execution Model", "9. Timeline & Milestones",
    "10. Closing & Q&A"]

    """
    return CompilePitchDeckOutlineOutput(
        slide_titles=[],
    )