from pydantic import BaseModel, Field
from typing import List


class CompilePitchDeckOutlineOutput(BaseModel):
    """Pydantic model for compile_pitch_deck_outline node outputs."""
    slide_titles: List[str] = (
        Field(..., description="An ordered list of the 10 slide titles for the investor pitch deck.")
    )


class DraftFeeStructureOutput(BaseModel):
    """Pydantic model for draft_fee_structure node outputs."""
    management_fee_percent: float = (
        Field(..., description="Management fee as a percentage of assets under management (AUM).")
    )
    performance_fee_percent: float = (
        Field(..., description="Performance fee as a percentage of returns generated by the fund.")
    )
    hurdle_rate_percent: float = (
        Field(..., description="Hurdle rate as a percentage of returns that must be achieved before performance fee is applied. Use 0 if not applicable.")
    )
    fee_commentary: str = (
        Field(..., description="Short explanatory sentence summarizing the fee structure and its alignment with fund objectives.")
    )


class EstimateSetupAndOperatingCostsOutput(BaseModel):
    """Pydantic model for estimate_setup_and_operating_costs node outputs."""
    service_provider_cost_usd: float = (
        Field(..., description="Estimated total annual cost in USD for all service providers listed")
    )
    technology_systems_cost_usd: float = (
        Field(..., description="Estimated total annual cost in USD for all required technology systems")
    )
    office_human_infrastructure_cost_usd: float = (
        Field(..., description="Estimated total annual cost in USD for office space, hardware, and human infrastructure")
    )


class CreateHiringPlanOutput(BaseModel):
    """Pydantic model for create_hiring_plan node outputs."""
    essential_roles: List[str] = (
        Field(..., description="List of essential FTE roles")
    )
    core_responsibilities: List[str] = (
        Field(..., description="List of core responsibilities for each role")
    )
    role_count: int = (
        Field(..., description="Total number of essential FTE roles")
    )


class DevelopTimelineAndMilestonesOutput(BaseModel):
    """Pydantic model for develop_timeline_and_milestones node outputs."""
    month_numbers: List[int] = (
        Field(..., description="Sequence of month numbers (1-12) for the roadmap")
    )
    milestone_names: List[str] = (
        Field(..., description="Short name of each milestone corresponding to each month")
    )
    milestone_descriptions: List[str] = (
        Field(..., description="Brief description of each milestone activity for the given month")
    )


def develop_timeline_and_milestones(compile_pitch_deck_outline_input: CompilePitchDeckOutlineOutput, draft_fee_structure_input: DraftFeeStructureOutput, estimate_setup_and_operating_costs_input: EstimateSetupAndOperatingCostsOutput, create_hiring_plan_input: CreateHiringPlanOutput, **kwargs) -> DevelopTimelineAndMilestonesOutput:
    """
    Generate a 12‑month implementation roadmap based on prerequisite inputs.

    Parameters
    ----------
    slide_titles : List[str]
        Ordered list of slide titles from the pitch deck outline.
    management_fee_percent : float
        Management fee percentage from the fee structure.
    performance_fee_percent : float
        Performance fee percentage from the fee structure.
    service_provider_cost_usd : float
        Annual cost of service providers.
    technology_systems_cost_usd : float
        Annual cost of technology systems.
    office_human_infrastructure_cost_usd : float
        Annual cost of office and human infrastructure.
    essential_roles : List[str]
        List of essential FTE roles from the hiring plan.
    core_responsibilities : List[str]
        Core responsibilities for each essential role.
    role_count : int
        Total number of essential FTE roles.

    Returns
    -------
    Dict[str, List[Union[int, str]]]
        A dictionary with keys 'month_numbers', 'milestone_names', and
        'milestone_descriptions', each mapping to a list of 12 items.

    Raises
    ------
    ValueError
        If any input list is empty or has mismatched lengths.
    TypeError
        If inputs are not of the expected types.

    Examples
    --------
    >>> timeline = develop_timeline_and_milestones(

    ...     slide_titles=["Objective", "Strategy", "Investor Profile", "Risk
    Controls", "Fee Model", "Operations", "Governance", "Capital Raise", "Tech
    Deployment", "Launch"],
    ...     management_fee_percent=1.5,

    ...     performance_fee_percent=20.0,

    ...     service_provider_cost_usd=300000.0,

    ...     technology_systems_cost_usd=250000.0,

    ...     office_human_infrastructure_cost_usd=400000.0,

    ...     essential_roles=["Portfolio Manager", "Compliance Officer",
    "Operations Lead"],
    ...     core_responsibilities=["Lead strategy", "Ensure regulatory
    compliance", "Oversee day‑to‑day ops"],
    ...     role_count=3

    >>> )
    {\n  "month_numbers": [1,2,3,4,5,6,7,8,9,10,11,12],\n  "milestone_names":
    ["Regulatory Filing","Provider Onboarding","Capital Raise","Tech
    Deployment","Launch","", "", "", "", "", "", ""],\n
    "milestone_descriptions": ["File SEC Form 13D with advisors", "Engage prime
    broker and custodian", "Secure $10M AUM", "Deploy OMS and risk engine", "Go
    live", "", "", "", "", "", "", ""]}

    """
    return DevelopTimelineAndMilestonesOutput(
        month_numbers=[],
        milestone_names=[],
        milestone_descriptions=[],
    )